apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  labels:
    app.kubernetes.io/name: kubecost
    app.kubernetes.io/component: cost-monitoring
    app.kubernetes.io/part-of: platform-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-tools
  source:
    repoURL: https://github.com/Adegokee/TeamDefenderKubecost.git
    path: .
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
